CREATE DATABASE IF NOT EXISTS CLINICA2;

USE CLINICA2;

CREATE TABLE MEDICO(
	NUMEROCRM BIGINT NOT NULL,
    ESTADOCRM CHAR(2) NOT NULL,
    NOMEMED VARCHAR(100) NOT NULL,
    
    CONSTRAINT MEDICO_PK PRIMARY KEY (NUMEROCRM, ESTADOCRM)
)ENGINE =INNODB;

CREATE TABLE PACIENTE(
	ID INT NOT NULL AUTO_INCREMENT,
    SEXO ENUM('M','F') NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    CEP BIGINT NOT NULL,
    DATANASCIMENTO DATE NOT NULL,
    NOMEPACIENTE VARCHAR(100) NOT NULL,
    CONSTRAINT PACIENTE_PK PRIMARY KEY(ID)
)ENGINE = INNODB;

CREATE TABLE ESPECIALIDADE(
	NOMEESPECIALIDADE VARCHAR(30) NOT NULL,
    IDESPECIALIDADE INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT ESPECIALIDADE_PK PRIMARY KEY (IDESPECIALIDADE)
) ENGINE = INNODB;

create table possuiespecialidade(
idespecialidade int not null,
numerocrm bigint not null,
estadocrm char(2) not null,

constraint possui_especialidade_UK unique(idespecialidade, numerocrm, estadocrm),
	constraint possui_especialidade_medico_FK foreign key(numerocrm,estadocrm)
		references medico(numerocrm,estadocrm)
		ON delete cascade,
        constraint possui_especialidade_FK foreign key(idespecialidade)
			references ESPECIALIDADE(IDESPECIALIDADE)
				on delete cascade
)engine = innodb;			

select * from possuiespecialidade;


CREATE TABLE CONSULTA(
	IDCONSULTA INT NOT NULL AUTO_INCREMENT,
    DATAHORA TIMESTAMP NOT NULL,
    NUMEROCRM BIGINT NOT NULL,
    ESTADOCRM CHAR(2) NOT NULL,
    IDPACIENTE INT NOT NULL,
    
    CONSTRAINT CONSULTA_PK PRIMARY KEY (IDCONSULTA),
    CONSTRAINT CONSULTA_MEDICO_FK FOREIGN  KEY(NUMEROCRM, ESTADOCRM) 
		REFERENCES MEDICO(NUMEROCRM, ESTADOCRM)
			ON DELETE CASCADE,
	CONSTRAINT CONSULTA_PACIENTE_FK FOREIGN KEY (IDPACIENTE)
		REFERENCES PACIENTE(ID)
			ON DELETE CASCADE
)ENGINE = INNODB;


create table telefone(
	telefone decimal(11) not null,
    idpaciente int not null,
    
    constraint telefone_UK unique (telefone, idpaciente),
    CONSTRAINT telefone_PACIENTE_FK FOREIGN KEY (IDPACIENTE)
		REFERENCES PACIENTE(ID)
			ON DELETE CASCADE
)engine = InnoDB;



select* from paciente;