CREATE DATABASE IF NOT EXISTS PAPELARIA;
USE PAPELARIA;

CREATE TABLE  CLIENTE(
NOME VARCHAR(100) NOT NULL,
CPF BIGINT NOT NULL,
EMAIL VARCHAR(100),
ENDERECO VARCHAR(150) NOT NULL,

CONSTRAINT CLIENTE_PK PRIMARY KEY (CPF)
)ENGINE = INNODB;


CREATE TABLE FUNCIONARIO(
MATRICULA BIGINT NOT NULL,
NOME VARCHAR(150) NOT NULL,
FUNCAO VARCHAR(30) NOT NULL,
EMAIL VARCHAR (150) NOT NULL,

CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (MATRICULA)
)ENGINE = INNODB;


CREATE TABLE VENDA(
ID_VENDA INT NOT NULL AUTO_INCREMENT,
MATRICULA  BIGINT NOT NULL,
CPF BIGINT NOT NULL,
LISTA_PRODUTO VARCHAR (100) NOT NULL,

CONSTRAINT VENDA_PK PRIMARY KEY (ID_VENDA),
CONSTRAINT MATRICULA_FK FOREIGN KEY (MATRICULA)
	REFERENCES FUNCIONARIO (MATRICULA)
    ON DELETE CASCADE
    
    ) ENGINE = INNODB;
    
    
    
    CREATE TABLE FORNECEDOR(
    CNPJ BIGINT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE DECIMAL (11) NOT NULL,
    ENDERECO VARCHAR (200) NOT NULL,
    EMAIL VARCHAR (150) NOT NULL,
    
    CONSTRAINT FORNECEDOR_PK PRIMARY KEY (CNPJ)
    ) ENGINE = INNODB;
    
    
 CREATE TABLE PRODUTO(
 CODIGO INT NOT NULL AUTO_INCREMENT,
 PRECO FLOAT NOT NULL,
 VALIDADE DATE NOT NULL,
 NOME VARCHAR (150) NOT NULL,
 DESCRICAO VARCHAR(200) NOT NULL,
 QUANTIDADE INT NOT NULL,
 CNPJ BIGINT NOT NULL,
 
 CONSTRAINT PRODUTO_PK PRIMARY KEY (CODIGO),
 CONSTRAINT CNPJ_FK FOREIGN KEY (CNPJ)
	REFERENCES FORNECEDOR (CNPJ)
    ON DELETE CASCADE
    
    ) ENGINE INNODB;
    
    
    

    
    